"""Initial migration

Revision ID: 000000000001
Revises: 
Create Date: 2026-02-09 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000000000001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if tables already exist (to handle transition from create_all to migrations)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'sessions' not in existing_tables:
        op.create_table('sessions',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('last_seen_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'presets' not in existing_tables:
        op.create_table('presets',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('preset_json', sa.JSON(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'debates' not in existing_tables:
        op.create_table('debates',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('session_id', sa.String(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('title', sa.String(), nullable=True),
            sa.Column('config_json', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('ended_at', sa.DateTime(), nullable=True),
            sa.Column('totals_json', sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_debates_session_id'), 'debates', ['session_id'], unique=False)
        op.create_index(op.f('ix_debates_status'), 'debates', ['status'], unique=False)
    
    if 'debate_participants' not in existing_tables:
        op.create_table('debate_participants',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('debate_id', sa.UUID(), nullable=False),
            sa.Column('role', sa.String(), nullable=False),
            sa.Column('model_id', sa.String(), nullable=False),
            sa.Column('persona_name', sa.String(), nullable=True),
            sa.Column('voice_name', sa.String(), nullable=True),
            sa.Column('avatar_url', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    if 'turns' not in existing_tables:
        op.create_table('turns',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('debate_id', sa.UUID(), nullable=False),
            sa.Column('seq_index', sa.Integer(), nullable=False),
            sa.Column('round_id', sa.String(), nullable=False),
            sa.Column('turn_type', sa.String(), nullable=False),
            sa.Column('speaker_id', sa.String(), nullable=False),
            sa.Column('speaker_name', sa.String(), nullable=False),
            sa.Column('text', sa.Text(), nullable=False),
            sa.Column('word_count', sa.Integer(), nullable=False),
            sa.Column('model_used', sa.String(), nullable=False),
            sa.Column('usage_json', sa.JSON(), nullable=False),
            sa.Column('retake_count', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_turns_debate_id'), 'turns', ['debate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_debate_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_table('debate_participants')
    op.drop_index(op.f('ix_debates_status'), table_name='debates')
    op.drop_index(op.f('ix_debates_session_id'), table_name='debates')
    op.drop_table('debates')
    op.drop_table('presets')
    op.drop_table('sessions')
    # ### end Alembic commands ###
